spring.application.name=translacat

# using spring security default form.
#spring.security.user.name=default_user
#spring.security.user.password=default_password

# MySQL configuration
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

# Resilience4j
resilience4j.circuitbreaker.instances.externalApiClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.externalApiClient.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.externalApiClient.wait-duration-in-open-state=10s
resilience4j.retry.instances.externalApiClient.max-attempts=3
resilience4j.retry.instances.externalApiClient.wait-duration=3s
resilience4j.timelimiter.instances.externalApiClient.timeout-duration=300s

resilience4j.ratelimiter.instances.geminiLimiter.limit-for-period=10
resilience4j.ratelimiter.instances.geminiLimiter.limit-refresh-period.seconds=10
resilience4j.ratelimiter.instances.geminiLimiter.timeout-duration.seconds=30

# web-client
web-client.timeout.response.seconds=300
web-client.timeout.connect.milli=10000

# google AI (gemini)
# docs
#  - https://aistudio.google.com/app/api-keys
#  - https://docs.spring.io/spring-ai/reference/api/chat/google-genai-chat.html
#  - https://ai.google.dev/gemini-api/docs/models?hl=ko
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.max-output-tokens=65536
spring.ai.google.genai.chat.options.response-mime-type=application/json
spring.ai.google.genai.chat.options.temperature=0.0
# permit harassment
spring.ai.google.genai.chat.options.safety-settings[0].category=HARM_CATEGORY_HARASSMENT
spring.ai.google.genai.chat.options.safety-settings[0].threshold=BLOCK_NONE
# permit hate speech
spring.ai.google.genai.chat.options.safety-settings[1].category=HARM_CATEGORY_HATE_SPEECH
spring.ai.google.genai.chat.options.safety-settings[1].threshold=BLOCK_NONE
# permit sexually_explicit
spring.ai.google.genai.chat.options.safety-settings[2].category=HARM_CATEGORY_SEXUALLY_EXPLICIT
spring.ai.google.genai.chat.options.safety-settings[2].threshold=BLOCK_NONE
# permit dangerous content
spring.ai.google.genai.chat.options.safety-settings[3].category=HARM_CATEGORY_DANGEROUS_CONTENT
spring.ai.google.genai.chat.options.safety-settings[3].threshold=BLOCK_NONE


# log level

# 1. Netty packet log off.
logging.level.reactor.netty.http.client=INFO

# 2. Spring AI log -> Info
logging.level.org.springframework.ai=INFO
logging.level.com.google.genai=INFO

# 3. query log.
# sql query only.
logging.level.jdbc.sqlonly=INFO
# SQL execution time off.
logging.level.jdbc.sqltiming=OFF
# jdbc audit off.
logging.level.jdbc.audit=OFF
# inquiry result table off.
logging.level.jdbc.resultset=OFF
# connection info off.
logging.level.jdbc.connection=OFF