# MySQL configuration
spring.datasource.url=${DB_URL}?rewriteBatchedStatements=true&sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# google info
# https://console.cloud.google.com/auth/clients/15694267434-61diaq8m1iuj3n8vo6bqn09vvk3rikfl.apps.googleusercontent.com?hl=ko&project=gen-lang-client-0347263829
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

# cors
cors.allowed-origin=${FRONTEND_URL}

# google AI (gemini)
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# google proxy
# https://script.google.com/home/?hl=ko&pli=1
external.google.proxy-url=${GOOGLE_PROXY_URL}
external.use-proxy=true

# result set table.
logging.level.jdbc.resultsettable=WARN

# furigana
sudachi.dictionary.path=/app/dictionaries/system_full.dic

# python AI Server
ai-server.url=${AI_SERVER_URL}
ai-server.api-key=${AI_SERVER_API_KEY}

# jwt
# 1000*60*60*24 (1 day)
jwt.token.expired.access=86400000
# 1000*60*60*24*7 (7 days)
jwt.token.expired.refresh=604800000
jwt.token.secret-key=${JWT_SECRET_KEY}

