name: BE Deploy to OCI

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/CatPjt-TranslaCat-be
            git pull origin main

            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

            docker build -t translacat-api .
            docker stop translacat-api-container || true
            docker rm translacat-api-container || true

            docker run -d -p 8080:8080 \
              --env-file .env \
              -e "SPRING_PROFILES_ACTIVE=prod" \
              --memory="1.5g" \
              --name translacat-api-container \
              translacat-api
            
            echo "Waiting for server to start (Max 5 minutes)..."
            SUCCESS=false
            for i in {1...60}; do
              if curl -s --head http://localhost:8080 | grep -E "200|401" > /dev/null
                echo "Success!"
                SUCCESS=true
                break
              fi

              echo "Attempt $i: Server not ready yet... waiting 5 seconds."
              sleep 5
            done

            if [ "$SUCCESS" = false ]; then
              echo "Error...."
              docker logs translacat-api-container
              exit 1
            fi
